---
- name: Playbook para instalar certificados y actualizar ca-trust
  hosts: all
  become: yes
  tasks:
    - name: Comprobar conectividad con el host
      ping:

    - name: Comprobar si los certificados ya están instalados
      stat:
        path: /etc/pki/ca-trust/source/anchors/{{ item }}
      register: cert_stat
      with_items:
        - cert1.crt
        - cert2.crt
        - cert3.crt

    - name: Copiar certificados si no están presentes
      copy:
        src: "{{ item }}"
        dest: /etc/pki/ca-trust/source/anchors/
      when: not item.stat.exists
      with_items: "{{ cert_stat.results }}"
      loop_control:
        loop_var: item

    - name: Actualizar el ca-trust
      command: update-ca-trust
      when: "'false' in (cert_stat.results | map(attribute='stat.exists') | list)"

    - name: Verificar la instalación de los certificados
      stat:
        path: /etc/pki/ca-trust/source/anchors/{{ item }}
      register: verify_cert_stat
      with_items:
        - cert1.crt
        - cert2.crt
        - cert3.crt

    - name: Asegurar que todos los certificados están instalados
      assert:
        that:
          - item.stat.exists
        fail_msg: "El certificado {{ item.item }} no está instalado correctamente"
      with_items: "{{ verify_cert_stat.results }}"
