---
- name: Playbook para instalar certificados y actualizar ca-trust
  hosts: all
  become: yes
  vars:
    cert_path: "/etc/ansible/playbooks/linux/pruebas/mcordero/cert"
    certs:
      - rootcaCert.pem
      - cert2.crt
      - cert3.crt
  tasks:
    - name: Comprobar conectividad con el host
      ping:

    - name: Asegurarse de que el directorio de destino existe
      file:
        path: /etc/pki/ca-trust/source/anchors
        state: directory
        mode: '0755'

    - name: Copiar certificados al destino usando fetch
      fetch:
        src: "{{ cert_path }}/{{ item }}"
        dest: /etc/pki/ca-trust/source/anchors/{{ item }}
        flat: yes
      with_items: "{{ certs }}"

    - name: Actualizar el ca-trust
      command: update-ca-trust

    - name: Verificar la instalación de los certificados
      stat:
        path: /etc/pki/ca-trust/source/anchors/{{ item }}
      register: verify_cert_stat
      with_items: "{{ certs }}"

    - name: Mostrar información sobre la verificación de certificados
      debug:
        msg: "Certificado {{ item }} existencia en destino: {{ item.stat.exists }}"
      with_items: "{{ verify_cert_stat.results }}"
      loop_control:
        loop_var: item

    - name: Asegurar que todos los certificados están instalados
      assert:
        that:
          - item.stat.exists
        fail_msg: "El certificado {{ item }} no está instalado correctamente"
      with_items: "{{ verify_cert_stat.results }}"
